version: "3"
services:
  mysql-target:
    build:
      dockerfile: ./sql/config/mysql-target.Dockerfile
      context: .
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-target-data:/var/lib/mysql
    ports: 
      - "33060:3306"
  mongo-target:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - mongo-target-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=citizix
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
volumes:
  mysql-target-data:
  mongo-target-data: