mapping = {
  "iso_code": "iso_code",
  "country": "name",
  "year": "year",
  "coal_prod_change_pct":       "coal_production_change_percent",
  "coal_prod_change_twh":       "coal_production_change_tw_h", 
  "gas_prod_change_pct":        "gas_production_change_percent", 
  "gas_prod_change_twh":        "gas_production_change_tw_h", 
  "oil_prod_change_pct":        "oil_production_change_percent", 
  "oil_prod_change_twh":        "oil_production_change_tw_h", 
  "energy_cons_change_pct":     "energy_consumption_change_percent", 
  "energy_cons_change_twh":     "energy_consumption_change_tw_h", 
  "biofuel_share_elec":         "biofuel_share_electricity",
  "biofuel_elec_per_capita":    "biofuel_electricity_per_capita", 
  "biofuel_cons_change_pct":    "biofuel_consumption_change_percent", 
  "biofuel_share_energy":       "biofuel_share_energy", 
  "biofuel_cons_change_twh":    "biofuel_consumption_change_tw_h",
  "biofuel_consumption":        "biofuel_consumption", 
  "biofuel_cons_per_capita":    "biofuel_consumption_per_capita", 
  "carbon_intensity_elec":      "carbon_intensity_electricity", 
  "coal_share_elec":            "coal_share_electricity", 
  "coal_cons_change_pct":       "coal_consumption_change_percent", 
  "coal_share_energy":          "coal_share_energy", 
  "coal_cons_change_twh":       "coal_consumption_change_tw_h", 
  "coal_consumption":           "coal_consumption",
  "coal_elec_per_capita":       "coal_electricity_per_capita", 
  "coal_cons_per_capita":       "coal_consumption_per_capita", 
  "coal_production":            "coal_production", 
  "coal_prod_per_capita":       "coal_production_per_capita", 
  "electricity_demand":         "electricity_demand", 
  "biofuel_electricity":        "biofuel_electricity", 
  "coal_electricity":           "coal_electricity", 
  "fossil_electricity":         "fossil_electricity", 
  "gas_electricity":            "gas_electricity", 
  "hydro_electricity":          "hydro_electricity", 
  "nuclear_electricity":        "nuclear_electricity", 
  "oil_electricity":            "oil_electricity", 
  "other_renewable_exc_biofuel_electricity":  "other_renewables_excluding_biofuel_electricity", 
  "other_renewable_electricity":  "other_renewables_electricity", 
  "renewables_electricity":       "renewables_electricity", 
  "solar_electricity":            "solar_electricity", 
  "wind_electricity":             "wind_electricity", 
  "electricity_generation":       "electricity_generation", 
  "greenhouse_gas_emissions":     "greenhouse_gas_emissions", 
  "energy_per_gdp":               "energy_per_gdp", 
  "energy_per_capita":            "energy_per_capita", 
  "fossil_cons_change_pct":       "fossil_consumption_change_percent", 
  "fossil_share_energy":          "fossil_share_energy", 
  "fossil_cons_change_twh":       "fossil_consumption_change_tw_h", 
  "fossil_fuel_consumption":      "fossil_fuel_consumption", 
  "fossil_energy_per_capita":     "fossil_energy_per_capita", 
  "fossil_cons_per_capita":       "fossil_consumption_per_capita", 
  "fossil_share_elec":            "fossil_share_electricity", 
  "gdp":                          "gdp", 
  "gas_share_elec":               "gas_share_electricity", 
  "gas_cons_change_pct":          "gas_consumption_change_percent", 
  "gas_share_energy":             "gas_share_energy", 
  "gas_cons_change_twh":          "gas_consumption_change_tw_h", 
  "gas_consumption":              "gas_consumption", 
  "gas_elec_per_capita":          "gas_electricity_per_capita", 
  "gas_energy_per_capita":        "gas_energy_per_capita", 
  "gas_production":               "gas_production", 
  "gas_prod_per_capita":          "gas_production_per_capita", 
  "hydro_share_elec":             "hydro_share_electricity", 
  "hydro_cons_change_pct":        "hydro_consumption_change_percent", 
  "hydro_share_energy":           "hydro_share_energy", 
  "hydro_cons_change_twh":        "hydro_consumption_change_tw_h", 
  "hydro_consumption":            "hydro_consumption", 
  "hydro_elec_per_capita":        "hydro_electricity_per_capita", 
  "hydro_energy_per_capita":      "hydro_energy_per_capita", 
  "low_carbon_share_elec":        "low_carbon_share_electricity", 
  "low_carbon_electricity":       "low_carbon_electricity", 
  "low_carbon_elec_per_capita":   "low_carbon_electricity_per_capita", 
  "low_carbon_cons_change_pct":   "low_carbon_consumption_change_percent", 
  "low_carbon_share_energy":      "low_carbon_share_energy", 
  "low_carbon_cons_change_twh":   "low_carbon_consumption_change_tw_h", 
  "low_carbon_consumption":       "low_carbon_consumption", 
  "low_carbon_energy_per_capita": "low_carbon_energy_per_capita", 
  "net_elec_imports_share_demand":"net_electricity_imports_as_share_demand", 
  "net_elec_imports":             "net_electricity_imports", 
  "nuclear_share_elec":           "nuclear_share_electricity", 
  "nuclear_cons_change_pct":      "nuclear_consumption_change_percent", 
  "nuclear_share_energy":         "nuclear_share_energy", 
  "nuclear_cons_change_twh":      "nuclear_consumption_change_tw_h", 
  "nuclear_consumption":          "nuclear_consumption", 
  "nuclear_elec_per_capita":      "nuclear_electricity_per_capita", 
  "nuclear_energy_per_capita":    "nuclear_energy_per_capita", 
  "oil_share_elec":               "oil_share_electricity", 
  "oil_cons_change_pct":          "oil_consumption_change_percent", 
  "oil_share_energy":             "oil_share_energy", 
  "oil_cons_change_twh":          "oil_consumption_change_tw_h", 
  "oil_consumption":              "oil_consumption", 
  "oil_elec_per_capita":          "oil_electricity_per_capita", 
  "oil_energy_per_capita":        "oil_energy_per_capita", 
  "oil_production":               "oil_production", 
  "oil_prod_per_capita":          "oil_production_per_capita", 
  "other_renewables_elec_per_capita_exc_biofuel": "other_renewables_electricity_per_capita_excluding_biofuel", 
  "other_renewables_elec_per_capita":             "other_renewables_electricity_per_capita", 
  "other_renewables_cons_change_pct":             "other_renewables_consumption_change_percent", 
  "other_renewables_share_energy":                "other_renewables_share_energy", 
  "other_renewables_cons_change_twh":             "other_renewables_consumption_change_tw_h", 
  "other_renewable_consumption":                  "other_renewables_consumption", 
  "other_renewables_share_elec_exc_biofuel":      "other_renewables_share_electricity_excluding_biofuel", 
  "other_renewables_share_elec":                  "other_renewables_share_electricity", 
  "other_renewables_energy_per_capita":           "other_renewables_energy_per_capita", 
  "per_capita_electricity":       "per_capita_electricity", 
  "population":                   "population", 
  "primary_energy_consumption":   "primary_energy_consumption", 
  "renewables_elec_per_capita":   "renewables_electricity_per_capita", 
  "renewables_share_elec":        "renewables_share_electricity", 
  "renewables_cons_change_pct":   "renewables_consumption_change_percent", 
  "renewables_share_energy":      "renewables_share_energy", 
  "renewables_cons_change_twh":   "renewables_consumption_change_tw_h", 
  "renewables_consumption":       "renewables_consumption", 
  "renewables_energy_per_capita": "renewables_energy_per_capita", 
  "solar_share_elec":             "solar_share_electricity", 
  "solar_cons_change_pct":        "solar_consumption_change_percent", 
  "solar_share_energy":           "solar_share_energy", 
  "solar_cons_change_twh":        "solar_consumption_change_tw_h", 
  "solar_consumption":            "solar_consumption", 
  "solar_elec_per_capita":        "solar_electricity_per_capita", 
  "solar_energy_per_capita":      "solar_energy_per_capita", 
  "wind_share_elec":              "wind_share_electricity", 
  "wind_cons_change_pct":         "wind_consumption_change_percent", 
  "wind_share_energy":            "wind_share_energy", 
  "wind_cons_change_twh":         "wind_consumption_change_tw_h", 
  "wind_consumption":             "wind_consumption", 
  "wind_elec_per_capita":         "wind_electricity_per_capita", 
  "wind_energy_per_capita":       "wind_energy_per_capita"
}

countryMapping = [
  'iso_code',
  'country'
]

tableMappings= {
  "CountryStatistics": [
    'year',
    'energy_cons_change_twh',
    'energy_cons_change_pct',
    'electricity_generation',
    'greenhouse_gas_emissions',
    'energy_per_gdp',
    'energy_per_capita',
    'net_elec_imports_share_demand',
    'net_elec_imports',
    'per_capita_electricity',
    'primary_energy_consumption',
    'electricity_demand',
    'carbon_intensity_elec',
    'gdp',
    'population'
  ],
  "Coal": [
    'year',
    'coal_prod_change_pct',
    'coal_prod_change_twh',
    'coal_share_elec',
    'coal_cons_change_pct',
    'coal_share_energy',
    'coal_cons_change_twh',
    'coal_consumption',
    'coal_elec_per_capita',
    'coal_cons_per_capita',
    'coal_production',
    'coal_prod_per_capita',
    'coal_electricity'
  ],
  "Gas": [
    'year',
    'gas_prod_change_pct',
    'gas_prod_change_twh',
    'gas_share_elec',
    'gas_cons_change_pct',
    'gas_share_energy',
    'gas_cons_change_twh',
    'gas_consumption',
    'gas_elec_per_capita',
    'gas_production',
    'gas_prod_per_capita',
    'gas_electricity',
    'gas_energy_per_capita'
  ],
  "Oil": [
    'year',
    'oil_prod_change_pct',
    'oil_prod_change_twh',
    'oil_share_elec',
    'oil_cons_change_pct',
    'oil_share_energy',
    'oil_cons_change_twh',
    'oil_consumption',
    'oil_elec_per_capita',
    'oil_production',
    'oil_prod_per_capita',
    'oil_electricity',
    'oil_energy_per_capita'
  ],
  "Hydro": [
    'year',
    'hydro_share_elec',
    'hydro_cons_change_pct',
    'hydro_share_energy',
    'hydro_cons_change_twh',
    'hydro_consumption',
    'hydro_elec_per_capita',
    'hydro_electricity',
    'hydro_energy_per_capita'
  ],
  "Biofuel": [
    'year',
    'biofuel_share_elec',
    'biofuel_cons_change_pct',
    'biofuel_share_energy',
    'biofuel_cons_change_twh',
    'biofuel_consumption',
    'biofuel_elec_per_capita',
    'biofuel_cons_per_capita',
    'biofuel_electricity'
  ],
  "Fossil": [
    'year',
    'fossil_share_elec',
    'fossil_cons_change_pct',
    'fossil_share_energy',
    'fossil_cons_change_twh',
    'fossil_fuel_consumption',
    'fossil_cons_per_capita',
    'fossil_electricity',
    'fossil_energy_per_capita'
  ],
  "Solar": [
    'year',
    'solar_share_elec',
    'solar_cons_change_pct',
    'solar_share_energy',
    'solar_cons_change_twh',
    'solar_consumption',
    'solar_elec_per_capita',
    'solar_electricity',
    'solar_energy_per_capita'
  ],
  "Nuclear": [
    'year',
    'nuclear_share_elec',
    'nuclear_cons_change_pct',
    'nuclear_share_energy',
    'nuclear_cons_change_twh',
    'nuclear_consumption',
    'nuclear_elec_per_capita',
    'nuclear_electricity',
    'nuclear_energy_per_capita'
  ],
  "Wind": [
    'year',
    'wind_share_elec',
    'wind_cons_change_pct',
    'wind_share_energy',
    'wind_cons_change_twh',
    'wind_consumption',
    'wind_elec_per_capita',
    'wind_electricity',
    'wind_energy_per_capita'
  ],
  "Renewables": [
    'year',
    'renewables_share_elec',
    'renewables_cons_change_pct',
    'renewables_share_energy',
    'renewables_cons_change_twh',
    'renewables_consumption',
    'renewables_elec_per_capita',
    'renewables_electricity',
    'renewables_energy_per_capita'
  ],
  "LowCarbon": [
    'year',
    'low_carbon_share_elec',
    'low_carbon_cons_change_pct',
    'low_carbon_share_energy',
    'low_carbon_cons_change_twh',
    'low_carbon_consumption',
    'low_carbon_elec_per_capita',
    'low_carbon_electricity',
    'low_carbon_energy_per_capita'
  ],
  "OtherRenewables": [
    'year',
    'other_renewables_share_elec',
    'other_renewables_cons_change_pct',
    'other_renewables_share_energy',
    'other_renewables_cons_change_twh',
    'other_renewable_consumption',
    'other_renewables_elec_per_capita',
    'other_renewable_electricity',
    'other_renewables_energy_per_capita',
    'other_renewable_exc_biofuel_electricity',
    'other_renewables_elec_per_capita_exc_biofuel',
    'other_renewables_share_elec_exc_biofuel'
  ]
}